### PR TITLE
Enable VCR debug logs

### PR DESCRIPTION
**Pull request by CAMOBAP795**
- https://github.com/metanorma/itubib/issues/4

### CODE REVIEW

**Comment by CAMOBAP795** [comment]
Issue reproduces on randomly on travis, appveyor & sometimes locally, if you have some guess please let me know

**Comment by CAMOBAP795** [comment]
I have reproduced issue locally with `while bundle exec rake; do :; done` command

Investigation continued

**Comment by CAMOBAP795** [comment]
Highly likely it's race condition somewhere https://github.com/vcr/vcr/issues/200 - marked as fixed but I will check history

**Comment by CAMOBAP795** [comment]
I have faced with same issue on https://github.com/metanorma/metanorma-standoc/ repository

**Comment by CAMOBAP795** [comment]
Ready for review

**Comment by ronaldtse** [comment]
@camobap795 I see that the Gemfile now points to a particular commit of the vcr gem — just wanted to let you know that this doesn’t propagate to the gemspec and gems that depend on this gem. I.e. the downstream gems that fail due to this gem won’t be fixed. 

Did you really want to merge this? (We should merge Ruby 2.5 for sure)

**Comment by CAMOBAP795** [comment]
@ronaldtse I think this is not the case, we do similar fix for https://github.com/metanorma/metanorma-gb/commit/2e5b3ebccc3799f5ebb01cb0c6622129ac1559cf

I just fixated commit because I 100% sure that there is no issues with this repo at this point

But let's wait for @opoudjis to check too

**Comment by ronaldtse** [comment]
OK merging this now, will open new issue to remove fixation of VCR gem.

**Pull request merged**
